import { IRecipe } from '../interfaces'

export const DUMMY_DATA: IRecipe[] = [
  {
    id: '0',
    title: 'Recipe 1',
    description: 'lorem lorem lorem lorem lorem lorem lorem',
    ingredients: [
      { name: 'Ingredients 1', quantity: 'gr', count: 10 },
      { name: 'Ingredients 2', quantity: 'gr', count: 15 },
      { name: 'Ingredients 3', quantity: 'ml', count: 20 },
    ],
    cookingTime: '10',
    isFavorite: true,
  },
  {
    id: '1',
    title: 'Recipe 2',
    description: 'lorem lorem lorem lorem lorem lorem lorem',
    ingredients: [
      { name: 'Ingredients 1', quantity: 'gr', count: 10 },
      { name: 'Ingredients 2', quantity: 'gr', count: 15 },
    ],
    cookingTime: '15',
    isFavorite: true,
  },
  {
    id: '2',
    title: 'Recipe 3',
    description: 'lorem lorem lorem lorem lorem lorem lorem',
    ingredients: [
      { name: 'Ingredients 1', quantity: 'gr', count: 15 },
      { name: 'Ingredients 2', quantity: 'gr', count: 20 },
      { name: 'Ingredients 3', quantity: 'ml', count: 25 },
      { name: 'Ingredients 4', quantity: 'gr', count: 30 },
      { name: 'Ingredients 5', quantity: 'gr', count: 35 },
      { name: 'Ingredients 6', quantity: 'gr', count: 40 },
    ],
    cookingTime: '25',
    isFavorite: false,
  },
  {
    id: '3',
    title: 'Recipe 4',
    description: 'lorem lorem lorem lorem lorem lorem lorem',
    ingredients: [{ name: 'Ingredients 1', quantity: 'gr', count: 15 }],
    cookingTime: '5',
    isFavorite: false,
  },
  {
    id: '4',
    title: 'Recipe 5',
    description: 'lorem lorem lorem lorem lorem lorem lorem',
    ingredients: [
      { name: 'Ingredients 1', quantity: 'gr', count: 15 },
      { name: 'Ingredients 2', quantity: 'gr', count: 20 },
      { name: 'Ingredients 3', quantity: 'ml', count: 25 },
    ],
    cookingTime: '35',
    isFavorite: true,
  },
  {
    id: '5',
    title: 'Recipe 6',
    description: 'lorem lorem lorem lorem lorem lorem lorem',
    ingredients: [
      { name: 'Ingredients 1', quantity: 'gr', count: 15 },
      { name: 'Ingredients 2', quantity: 'gr', count: 20 },
      { name: 'Ingredients 3', quantity: 'ml', count: 25 },
      { name: 'Ingredients 4', quantity: 'gr', count: 30 },
      { name: 'Ingredients 5', quantity: 'gr', count: 35 },
      { name: 'Ingredients 6', quantity: 'gr', count: 40 },
      { name: 'Ingredients 7', quantity: 'ml', count: 45 },
    ],
    cookingTime: '5',
    isFavorite: true,
  },
  {
    id: '6',
    title: 'Recipe 7',
    description: 'lorem lorem lorem lorem lorem lorem lorem',
    ingredients: [
      { name: 'Ingredients 1', quantity: 'gr', count: 15 },
      { name: 'Ingredients 2', quantity: 'gr', count: 20 },
      { name: 'Ingredients 3', quantity: 'ml', count: 25 },
    ],
    cookingTime: '20',
    isFavorite: true,
  },
  {
    id: '7',
    title: 'Recipe 8',
    description: 'lorem lorem lorem lorem lorem lorem lorem',
    ingredients: [
      { name: 'Ingredients 1', quantity: 'gr', count: 15 },
      { name: 'Ingredients 2', quantity: 'gr', count: 20 },
      { name: 'Ingredients 3', quantity: 'ml', count: 25 },
      { name: 'Ingredients 4', quantity: 'gr', count: 30 },
    ],
    cookingTime: '15',
    isFavorite: false,
  },
  {
    id: '8',
    title: 'Recipe 9',
    description: 'lorem lorem lorem lorem lorem lorem lorem',
    ingredients: [
      { name: 'Ingredients 1', quantity: 'ml', count: 15 },
      { name: 'Ingredients 2', quantity: 'gr', count: 20 },
    ],
    cookingTime: '15',
    isFavorite: false,
  },
]
